name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15]
        include:
          - os: macos-15
            xcode: "16.4"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

      - name: Show Swift version
        run: swift --version

      - name: Cache Swift Package Manager
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/.cache/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.swift', 'Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Resolve dependencies
        run: swift package resolve

      - name: Build debug
        run: swift build --configuration debug

      - name: Build release
        run: swift build --configuration release

      - name: Run tests
        run: swift test --configuration debug --enable-code-coverage

      - name: Generate code coverage report
        run: |
          xcrun llvm-cov export -format="lcov" \
            .build/debug/SwiftDependencyAuditPackageTests.xctest/Contents/MacOS/SwiftDependencyAuditPackageTests \
            -instr-profile=.build/debug/codecov/default.profdata > coverage.lcov
        continue-on-error: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: coverage.lcov
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Test CLI functionality
        run: |
          swift run swift-dependency-audit --help
          swift run swift-dependency-audit . --verbose --exclude-tests

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}
          path: |
            .build/release/swift-dependency-audit
          retention-days: 7

  lint:
    name: Lint and Format Check
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer

      - name: Cache Swift Package Manager
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/.cache/org.swift.swiftpm
          key: ${{ runner.os }}-spm-lint-${{ hashFiles('Package.swift', 'Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-lint-
            ${{ runner.os }}-spm-

      - name: Check Swift format
        run: |
          # Install swift-format if available
          if command -v swift-format &> /dev/null; then
            swift-format --version
            find Sources Tests -name "*.swift" | xargs swift-format --mode diff
          else
            echo "swift-format not available, skipping format check"
          fi
        continue-on-error: true

      - name: Swift build warnings check
        run: |
          swift build --configuration release 2>&1 | tee build.log
          if grep -q "warning:" build.log; then
            echo "⚠️  Build warnings found:"
            grep "warning:" build.log
            exit 1
          fi
